# ClickHouse Server Configuration (YAML)
logger:
  level: warning
  log: /var/log/clickhouse-server/clickhouse-server.log
  errorlog: /var/log/clickhouse-server/clickhouse-server.err.log
  size: 1000M
  count: 3

# Portas de comunicação
http_port: 8123
tcp_port: 9000

# Força o Clickhouse a escutar apenas na interface IPv4 para evitar conflito com [::]
listen_host: 0.0.0.0

# Caminhos de armazenamento internos
path: /var/lib/clickhouse/
tmp_path: /var/lib/clickhouse/tmp/
user_files_path: /var/lib/clickhouse/user_files/
format_schema_path: /var/lib/clickhouse/format_schemas/

# REMOVIDO: O bloco user_directories foi removido.
# A imagem oficial gerencia o carregamento do users.d/ automaticamente.
